### ISSUE TITLE
Debian's own packaging causes loss of environment variables when pulling docker image

### ISSUE THREAD

**Issue by aroffringa** [sylabs/singularity#852] opened 2022-06-07 15:41 UTC
### Version of Singularity:

The problem occurs with `singularity-ce version 3.9.9+ds1` ; reproducable on both a Ubuntu2022 and Debian machine.

Using `singularity-ce version 3.9.4` gives the right result.

### Expected behavior

I'm using a Docker image that has PYTHONPATH set using an ENV cmd, as well as some other env vars. When we pull it with Singularity 3.9.4, the variables get set. When we pull it with Singularity 3.9.9, it does not get set. Example:

The expected behaviour (as shown by 3.9.4) is:
```
singularity pull --name astronrd_linc.sif docker://astronrd/linc
singularity exec --contain --cleanenv astronrd_linc.sif bash
Singularity> echo $PYTHONPATH
/usr/local/bin
Singularity> echo $LINC_DATA_ROOT
/usr/local/share/linc
```

### Actual behavior

3.9.9 shows:
```
singularity pull --name astronrd_linc.sif docker://astronrd/linc
singularity exec --contain --cleanenv astronrd_linc.sif bash
Singularity> echo $PYTHONPATH

Singularity> echo $LINC_DATA_ROOT

Singularity>
```
This seems to be an issue in the "pull" command. When we pull the container using 3.9.4, and then exec it in 3.9.9, it works as expected. Changing the `pull` to a `build` does not fix the issue.

### What OS/distro are you running

Appears both on this:
```
Linux bookworm/sid"
NAME="Debian GNU/Linux"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```
and on this:
```
$ cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```

### How did you install Singularity

From the Debian/Ubuntu packages.

(The 3.9.4 version that does work runs on a different machine)

**Comment by dtrudg** [comment] 2022-06-07 16:27
There was a change at 3.9.5 to fix an environment variable precedence bug that came in via a dependency update in 3.9.2.

I'll look into what's going on here as soon as possible. What would help is if you can confirm...

* If your host environment contains any variables of the same names, or prefixed `SINGULARITYENV_`.
* Whether the issue reproduces in `3.9.5` and the current supported version, `3.10.0`.

I'll get around to this, but if you are able it would save a bit of time. Thanks.

It's a bit puzzling so far, as we do have e2e tests that check pulling `ENV` variable from a docker image. I.E. 

https://github.com/sylabs/singularity/blob/c80f1b5621012e9461eb5af5a3e1a2c4a2c85e8e/e2e/env/env.go#L179

Possible that the `--cleanenv` path has acquired a bug somewhere.

**Comment by aroffringa** [comment] 2022-06-07 18:31
Thanks for the reply!

Leaving  out `--cleanenv` produces the same issue (which I guess is logical if the issue is in the `pull`). I do not have any `SINGULARITYENV_` vars set. I've tried unsetting `PYTHONPATH` before running, and it still results in the same issue.

I tried installing other Singularity versions, but due to https://github.com/sylabs/singularity/issues/853 I'm unable to install a non-packaged version on my system, so I'm afraid I can't help there. However the docker container producing the issue is publicly available, so you should be able to try yourself easily.

**Comment by dtrudg** [comment] 2022-06-07 21:07
I've tried to reproduce here, and with a stock `singularity-ce version 3.9.9` there is no bug visible:

```
$ singularity --version
singularity-ce version 3.9.9

03:55 PM $ singularity pull --name astronrd_linc.sif docker://astronrd/linc
INFO:    Converting OCI blobs to SIF format
INFO:    Starting build...
Getting image source signatures
Copying blob 8e5c1b329fe3 done  
Copying blob 954a6388c050 done  
Copying blob 1c36a59041e6 done  
Copying blob fd4d78c72737 done  
Copying blob 5c70c1a617fa done  
Copying blob 07ea3b8bb67c done  
Copying blob 08185c53ea0a done  
Copying config 2fa1d176f4 done  
Writing manifest to image destination
Storing signatures
2022/06/07 15:56:07  info unpack layer: sha256:8e5c1b329fe39c318c0d49821b339fb94a215c5dc0a2898c8030b5a4d091bcba
2022/06/07 15:56:07  info unpack layer: sha256:fd4d78c72737967eb3732866c82e99013d3f54708202619613fd7579c43f6148
2022/06/07 15:56:15  info unpack layer: sha256:1c36a59041e6b2809ac64ffc028f5832b091c050958ef0ba9e54725053647212
2022/06/07 15:56:15  info unpack layer: sha256:5c70c1a617fa9707f1182f116cbb9dd2f7687267fd27133b1cb9fab3848a705c
2022/06/07 15:56:21  info unpack layer: sha256:07ea3b8bb67cd7d3b9930a6bbb041285edacb182c75d4dcc0c1007d2b080a644
2022/06/07 15:56:21  info unpack layer: sha256:954a6388c05015d6095995642ad2efe293e34bf7a09c19c9785e72dae7f3222c
2022/06/07 15:56:23  info unpack layer: sha256:08185c53ea0aa6f1515af7008e654a01c6200345c1997e1a70c974394d17db03
INFO:    Creating SIF file...

03:56 PM $ singularity exec --contain --cleanenv astronrd_linc.sif bash
Singularity> echo $PYTHONPATH
/usr/local/bin
Singularity> echo $LINC_DATA_ROOT
/usr/local/share/linc
Singularity> exit
```

Your version string `singularity-ce version 3.9.9+ds1` indicates that you are installing the Debian maintained package of singularity-ce, rather than our own packaging (from the GitHub release page).

I'm afraid we don't have any control over, and don't support the Debian package. As for many Go projects, Debian replaces our specific version pinned and tested Go dependencies with different versions of those dependencies that are packaged in Debian already. We don't test against the versions of the dependencies in Debian, and they can cause issues, which is the most likely cause of this bug.

For example, SingularityCE 3.9.9 calls for the dependency `mvdan.cc/sh/v3 v3.4.3-0.20220202175809-113ed667a8a7` in its `go.mod` file. This is a critical dependency for environment processing etc. The current Debian packaging is using Debian's `golang-mvdan-sh-dev` package in place of our pinned dependency. This Debian package provides a different version of `mvdan.cc/sh`.

I'm afraid you will need to report the bug to the maintainer of the Debian package, as it appears to be specific to the Debian packaging, and not present in our own SingularityCE 3.9.9 release.

Note also that the Ubuntu packages on our GitHub release page generally work under Debian of similar age.

**Comment by aroffringa** [comment] 2022-06-07 21:14
I've now been able to install 3.10 and indeed there things work as intended. I will file a big for the Debian package. Thanks for the analysis and help!

**Comment by dtrudg** [comment] 2022-06-07 21:19
> I've now been able to install 3.10 and indeed there things work as intended. I will file a bug for the Debian package. Thanks for the analysis and help!

Great, thanks. Just a further heads up that our own ubuntu focal packages from the releases page here on GitHub will work on Debian bookworm/sid... e.g. here is the 3.9.9-focal package installed there...

```
root@0ca1b0e2b4ce:/# dpkg -l | grep singularity
ii  singularity-ce           3.9.9-focal                       amd64        SingularityCE is the Community Edition of Singularity, an
root@0ca1b0e2b4ce:/# singularity pull --name astronrd_linc.sif docker://astronrd/linc
INFO:    Converting OCI blobs to SIF format
INFO:    Starting build...
Getting image source signatures
Copying blob fd4d78c72737 done  
Copying blob 8e5c1b329fe3 done  
Copying blob 954a6388c050 done  
Copying blob 1c36a59041e6 done  
Copying blob 07ea3b8bb67c done  
Copying blob 5c70c1a617fa done  
Copying blob 08185c53ea0a done  
Copying config 2fa1d176f4 done  
Writing manifest to image destination
Storing signatures
2022/06/07 21:16:41  info unpack layer: sha256:8e5c1b329fe39c318c0d49821b339fb94a215c5dc0a2898c8030b5a4d091bcba
2022/06/07 21:16:42  info unpack layer: sha256:fd4d78c72737967eb3732866c82e99013d3f54708202619613fd7579c43f6148
2022/06/07 21:16:49  info unpack layer: sha256:1c36a59041e6b2809ac64ffc028f5832b091c050958ef0ba9e54725053647212
2022/06/07 21:16:49  info unpack layer: sha256:5c70c1a617fa9707f1182f116cbb9dd2f7687267fd27133b1cb9fab3848a705c
2022/06/07 21:16:55  info unpack layer: sha256:07ea3b8bb67cd7d3b9930a6bbb041285edacb182c75d4dcc0c1007d2b080a644
2022/06/07 21:16:55  info unpack layer: sha256:954a6388c05015d6095995642ad2efe293e34bf7a09c19c9785e72dae7f3222c
2022/06/07 21:16:57  info unpack layer: sha256:08185c53ea0aa6f1515af7008e654a01c6200345c1997e1a70c974394d17db03
INFO:    Creating SIF file...
root@0ca1b0e2b4ce:/# singularity exec --contain --cleanenv astronrd_linc.sif bash
Singularity> echo $PYTHONPATH
/usr/local/bin
Singularity> echo $LINC_DATA_ROOT
/usr/local/share/linc
Singularity> exit
```

... so very confident this is a Debian packaging issue. Will close this now given it's not our bug, but it'll appear in search results for anyone coming across the same issue.

**Closed** 2022-06-07 21:37 UTC

**Comment by dtrudg** [comment] 2022-06-08 15:38
Hi @aroffringa - I did a little bit more digging, as I was curious how a dependency version change would cause this particular error. I now don't think it's directly from a dependency version difference, but it's indirect through a patch instead.

Debian has this patch: https://salsa.debian.org/hpc-team/singularity-container/-/blob/master/debian/patches/conveyorPacker_oci.patch

... which makes that function return an empty `imgspecv1.ImageConfig{}` always... instead of the ImageConfig from the Docker/OCI image.

Later on we retrieve the `ENV` values out of the config that this function returns. But with the Debian patch the config is going to be empty, so no `ENV` is seen.

I think this patch was done because of an incompatibility with the version of a dependency they have switched to, versus our pinned version. However it's the bad patch causing the error with generating Docker containers, not the dependency change itself.

If you want to communicate this to the downstream Debian bug report directly, that might assist.

**Comment by aroffringa** [comment] 2022-06-09 06:53
Thanks for locating the issue @dtrudg , I've added that information to the Debian bug ticket.

**Comment by nileshpatra** [comment] 2022-06-17 06:04
@aroffringa I have uploaded a revision `3.10.0+ds2-3` on top of this which seems to fix it for me atleast locally.

```
$ singularity version                                             
3.10.0+ds2
$ singularity pull --name astronrd_linc.sif docker://astronrd/linc
INFO:    Converting OCI blobs to SIF format
INFO:    Starting build...
Getting image source signatures
Copying blob 8e5c1b329fe3 done  
Copying blob 26caa71286bd done  
Copying blob a17830e1ea72 done  
Copying blob fe1afebc6089 done  
Copying blob c555c941bc15 done  
Copying blob 8bc7478a8517 done  
Copying blob 74fef9b9e9d4 done  
Copying config 1d34bfe188 done  
Writing manifest to image destination
Storing signatures
2022/06/17 11:02:19  info unpack layer: sha256:8e5c1b329fe39c318c0d49821b339fb94a215c5dc0a2898c8030b5a4d091bcba
2022/06/17 11:02:19  info unpack layer: sha256:26caa71286bdf1af8ef4166fbe965097704fb048554607ed116d4b8f18a668f6
2022/06/17 11:02:24  info unpack layer: sha256:a17830e1ea72798e9b13c68150043f5545d2f1ea17dc30df330a9c8301710965
2022/06/17 11:02:25  info unpack layer: sha256:fe1afebc60894b2e27b57f50e606ab001388a57a017db5d523dcfd0714929c51
2022/06/17 11:02:29  info unpack layer: sha256:c555c941bc15f15b86c8a5bd07420e56411a648e17909af5a75a838b3c7d10ab
2022/06/17 11:02:29  info unpack layer: sha256:8bc7478a8517c7b755cd5fb43ef027a5bd11a3201a5b2c8833ccf85c6824d05a
2022/06/17 11:02:30  info unpack layer: sha256:74fef9b9e9d4abf5f16e19e24726b9cd38a8bd42989e0abc5c581f0d1fa1a701
INFO:    Creating SIF file...
$ singularity exec --contain --cleanenv astronrd_linc.sif bash
Singularity> echo $PYTHONPATH
/usr/local/bin
Singularity> echo $LINC_DATA_ROOT
/usr/local/share/linc
Singularity> exit
```

I have closed the corresponding debian bug report and also replied to your email there. Can I ask you to please test this once?

(It might take some time for it to propagate it to debian FTP mirrors -- please ensure it is `3.10.0+ds2-3` you are using with `apt policy singularity-container` :))
