### ISSUE TITLE
What about %init that get's executed whenever the container is started?

### ISSUE THREAD

**Issue by stmlange** [sylabs/singularity#1161] opened 2022-12-05 08:39 UTC
**Is your feature request related to a problem? Please describe.**
Singularity currently allows to launch or open a container in various ways (e.g. `singularity run`, `singularity exec`, `singularity shell`, ... ?).
Maybe I'm missing it, but I haven't found an easy and reliable way to execute a specific set of commands whenever a container is actually initialized or started. IMHO such section could be used to verify if container can be run on the host, or setup some symlinks so binaries or libraries can be adjusted to the actual underlying host system.

I would not expect that one would run commands like `apt-get` in here, but in theory every command should be allowed.

**Describe the solution you'd like**
Have an `%init` section that get's executed whenever a container is actually initialized or started (e.g. `singularity run`, `singularity exec`, `singularity shell`, ... ?)

**Describe alternatives you've considered**
- systemd, init.d but those are very specific for *unix systems
- add the relevant startup script in `.singularity/env/foo.sh` which happens to be sourced (however this sounds like a hack for me)

**Comment by dtrudg** [comment] 2022-12-05 10:33
Hi. Thanks for opening this issue!

This has been something that has come up periodically, and it hasn't been implemented in the past because...

`singularity run` using the `%runscript` is the generic 'start the container' method. Because there is a `%runscript` here you can implement anything that you need. What some do is to have a `%runscript` that can handle arguments to simulate `exec` or `shell` after the initialization has been performed.

`singularity exec` and `singularity shell` are explicitly to exec *only* the specified binary, or the shell in the container. It's generally understood that nothing else will be executed in the container with these commands, outside of the `%environment` section / env scripts, which are run with an embedded limited shell interpreter. I'd tend to think that modifying this behavior at this point would be for a major version, or behind a flag. There are, for example, people who are using `singularity shell` to drop into a container and examine it before they `run` it... and we'd not want to change that flow (imperfect as it is).

Going forward we are moving more toward the OCI model, with an OCI runtime mode and better OCI compatibility. Introducing an `%init` would actually move us backward as it's not a concept in OCI containers. This is probably the biggest blocker for the feature request at the present time.

Regarding the reasons for the feature...

> such section could be used to verify if container can be run on the host, or setup some symlinks so binaries or libraries can be adjusted to the actual underlying host system.

... verification of whether a container can be run is probably better handled by metadata stored in the SIF. Ideally a scheduler or other process should be able to check if the container can run, without actually running it. I do definitely concede that this is difficult, though.

The adjustment of symlinks etc. is an interesting problem to attempt to address. Perhaps you could give a bit more detail? Generally for different hosts we'd expect host libraries to be bound into the same place in the container, so it'd be good to know more about the issues you are seeing that need symlink changes etc.

What I'd generally sugggest is that for feature requests like this, is that it would be great to provide detailed examples of real-world situations that are diffcult at present, and would be solved by the requested feature. They are also often good to raise on the mailing list and/or slack channel to guage interest.

**Comment by stmlange** [comment] 2022-12-05 11:19
Hi,
thanks for your feedback and detailed explanation!
I think the main reason is that even if I specify a runscript section that does this "init" there is no way of telling the consumers of the container that they need to run the container (instead of executing it).
Sample section:
```
%runscript
  magic_init
  exec /bin/bash "$@"
```

The perhaps weird issue I'm facing is that we have host systems that use different [slurm](https://slurm.schedmd.com/quickstart.html) versions. If you don't know slurm think of a scheduling system. Now the problem is essentially that we have multiple systems (think of prod, test, dev) where different slurm versions are running. Those versions may be incompatible (on dev think of version 23, on test 22 and on prod 20). The [pyslurm](https://github.com/PySlurm/pyslurm) seems to try to load some native libraries (e.g. from /etc/lib/slurm.so). There is generally no issue compiling all three version into the container, the problem is really "what version is the right one". Hence the idea was born that an init-script could check what version is running on the actual underlying host and create the correct symlink so the python stuff can work on all systems.
Yes there could be alternatives like the [rest api](https://slurm.schedmd.com/rest.html), and perhaps some tinkering with some python internals where such library is loaded from....

If someone wants to drop into a shell and just experiment, maybe hide this option behind a flag (--execute-init). As an additional security consideration this should be executed before the host-filesystem is mounted. Otherwise a bad actor could `rm -rf /home`. I'd imagine it like an additional %post section, but for runtime.

Hope that clarifies, I'm aware that there might be 123868123 alternatives to get to the same goal, or to get the tooling working, but I thought maybe someone else would be interested in such an init-section too :-)

If you feel this contradicts somehow with the path where singularity is moving to, please feel free to close this request :-)

**Comment by stmlange** [comment] 2022-12-06 18:18
Another possible alternative I have now considered is %appinstall, but that doesn't work either: https://github.com/sylabs/singularity/issues/1171

**Comment by dtrudg** [comment] 2022-12-07 09:58
> Hi, thanks for your feedback and detailed explanation! I think the main reason is that even if I specify a runscript section that does this "init" there is no way of telling the consumers of the container that they need to run the container (instead of executing it).

This sounds like the users have a misunderstanding of the intention of `run` vs `exec`.

* `run` is to run the container, as the creator of the container intended... including any startup script etc.
* `exec` is to run a single command, and only that command, in the container. This is the user's choice and explicitly *not* running the container as the creator of the container intended. It's really 'exec a command in the container' and not 'exec the container' - I think this is where people get tripped up in their understanding.

The more I think about this, the less likely we are to change it, tbh. Other runtimes have the same approach. E.g. for Docker, `run` will follow the `ENTRYPOINT/CMD` the container creator set, but `exec` will just run the command the user specifies.

If you think we can improve the documentation anywhere, that would be good.

Also note that Singularity supports adding a `%help` section to a definition file - although this is rarely used:

https://docs.sylabs.io/guides/latest/user-guide/definition_files.html#help


> The perhaps weird issue I'm facing is that we have host systems that use different [slurm](https://slurm.schedmd.com/quickstart.html) versions. If you don't know slurm think of a scheduling system. Now the problem is essentially that we have multiple systems (think of prod, test, dev) where different slurm versions are running. Those versions may be incompatible (on dev think of version 23, on test 22 and on prod 20). The [pyslurm](https://github.com/PySlurm/pyslurm) seems to try to load some native libraries (e.g. from /etc/lib/slurm.so). There is generally no issue compiling all three version into the container, the problem is really "what version is the right one". Hence the idea was born that an init-script could check what version is running on the actual underlying host and create the correct symlink so the python stuff can work on all systems. Yes there could be alternatives like the [rest api](https://slurm.schedmd.com/rest.html), and perhaps some tinkering with some python internals where such library is loaded from....

You might be able to have a conditional in %environment that looks for an env var indicating the version on the host, and sets `LD_LIBRARY_PATH` in the container based on that, to include the dir with the correct libraries, rather than symlinking the libraries?

> Another possible alternative I have now considered is %appinstall, but that doesn't work either: https://github.com/sylabs/singularity/issues/1171

I've replied separately on that one. I'm afraid it's not a bug... singularity is implementing the SCIF spec. Rather the documentation is poor.

**Comment by dtrudg** [comment] 2023-09-20 10:03
This is something that isn't really possible to reconcile with OCI run vs exec behaviour, and we are moving more toward OCI rather than away, so I'm afraid this won't be implemented.

**Closed by dtrudg** 2023-09-20 10:03 UTC
Labels: enhancement, needs more info
