### ISSUE TITLE
tmpfs error using singularity with PID namespace on RHEL 8.8

### ISSUE THREAD

**Issue by adnan-umich** [sylabs/singularity#2995] opened 2024-06-12 17:41 UTC
**Version of Singularity**
WIth singularity versions:
* 3.11.1
* 3.11.5
* 4.1.2

**Describe the bug**
We have an HPC system with Slurm, and RHEL 8.6 OS. We had Singularity CE 3.11.1 installed and were able to execute singularity exec using the PID namespace. I.e commands similar in nature to this:

```singularity  exec --pid --no-home -B /home/adnanzai/software --bind /tmp:/tmp /sw/pkgs/med/alphafold/2.3.2/alphafold.sif /bin/bash -c "hostname"```

Unfortunately, post SLURM upgrade, and RHEL OS upgrade to 8.8, anytime we now run the above command we get an error akin to this:

```singularity  exec --pid --no-home -B /home/adnanzai/software --bind /tmp:/tmp /sw/pkgs/med/alphafold/2.3.2/alphafold.sif /bin/bash -c "hostname"
free(): invalid pointer
FATAL:   container creation failed: mount tmpfs->/opt/singularity/4.1.2/var/singularity/mnt/session error: while mounting tmpfs: can't mount tmpfs filesystem to /opt/singularity/4.1.2/var/singularity/mnt/session: write unix @->@: write: broken pipe
```

If I remove the `--pid` flag then the above command works again, so that leads me to believe this is an issue with using the PID namespace again? We get the same problem with CE  versions `3.11.5` and `4.1.2`
I found a potential, but risky solution of reinstalling Singularity CE 3.11.1/3.11.5 or 4.1.2 without SETUID by using --without-setuid.
My questions is, does running an unprivileged singularity CE pose security threats on a multi-user HPC system? And honestly, what could have caused this breaking change in the first place? I'm hoping to find some solutions.

**To Reproduce**

Run ```
singularity  exec --pid --no-home -B /home/adnanzai/software --bind /tmp:/tmp /sw/pkgs/med/alphafold/2.3.2/alphafold.sif /bin/bash -c "hostname"
``` 

The container can be any linux container, we tried general Ubuntu images as well (pulled from Docker)

**Expected behavior**
It should run without error and print the name of the host. 

**OS / Linux Distribution**
```
NAME="Red Hat Enterprise Linux"
VERSION="8.8 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Red Hat Enterprise Linux 8.8 (Ootpa)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:8::baseos"
HOME_URL="https://www.redhat.com/"
DOCUMENTATION_URL="https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_BUGZILLA_PRODUCT_VERSION=8.8
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.8"
```
**Installation Method**
Singularity build from source, using Go version go1.22.4 linux/amd64 and go1.22.1 (precompiled binaries pulled from Google).
```
./mconfig && \
    make -C ./builddir && \
    sudo make -C ./builddir install```

**Additional context**
This is an HPC system running Slurm 23.11.6

**Comment by dtrudg** [comment] 2024-06-13 08:39
The RHEL 8.8 minor release is now over a year old, with the current release being 8.10. Also note that v4.1.3 is the current SingularityCE release. Therefore I am testing the following on RHEL 8.10 and with SIngularityCE v4.1.3:

```
$ cat /etc/os-release
NAME="Red Hat Enterprise Linux"
VERSION="8.10 (Ootpa)"

$ uname -a
Linux dev-rhel8 4.18.0-553.5.1.el8_10.x86_64 #1 SMP Tue May 21 03:13:04 EDT 2024 x86_64 x86_64 x86_64 GNU/Linux

$ go version
go version go1.22.4 linux/amd64

$ singularity --version
singularity-ce version 4.1.3

$ singularity exec --pid --no-home ubuntu_latest.sif /bin/bash -c "hostname"
dev-rhel8
```

As can be seen above, there is no issue running with the `--pid` namespace in this configuration, so it is likely that the error is related to some specific issue with your system configuration.

There isn't a lot we can suggest other than:

* Try again with the latest SingularityCE v4.1.3.
* Check whether updating to the RHEL 8.10 kernel version on a test system fixes the problem (which would suggest it is related to an issue in the 8.8 kernel).
* Collect detailed information about the crash - i.e. output of `singularity --debug`, any errors show in `dmesg`, output showing syscalls from using `strace -f` or gdb. This would be required to further investigate the issue given that it doesn't replicate in our test RHEL8 environment.

**Comment by adnan-umich** [comment] 2024-06-14 04:42
Hello @dtrudg thank you for your response. Please note that I already tried three versions of singularity all with the exact same issue (3.11.1, 3.11.5, and 4.1.2). With your suggestion, I was able to make this work with 4.1.3 on RHEL 8.8. I will do some more testing to confirm everything and get back to you ASAP.

**Comment by dtrudg** [comment] 2024-06-14 08:17
@adnan-umich - if it's working with 4.1.3 on RHEL 8.8 then that's great.

For the open source SingularityCE project we only investigate issues and develop fixes for things that can be reproduced with the latest version, 4.1.3 in this case, so I'm afraid that any issues with 3.11.1 / 3.11.5 / 4.1.2 are out of scope.

If you find a problem with 4.1.3, please don't hesitate to report it with additional information as in my previous post.

**Comment by adnan-umich** [comment] 2024-06-14 19:19
Thank you. Honestly, Im really baffled how 4.1.2 didn't work for us, but just by upgrading to 4.1.3 solved the issue. Could you please provide some insight into what exactly changed from 4.1.2 to 4.1.3? What change could have *fixed* this issue for us?

**Comment by dtrudg** [comment] 2024-06-17 08:04
The diff between the versions is - https://github.com/sylabs/singularity/compare/v4.1.2...v4.1.3

There is nothing that's an explicit fix in the SingularityCE code. However, many dependencies were updated and the issue is most likely related to one of those.

**Closed by dtrudg** 2024-06-17 08:04 UTC
Labels: needs more info
