### ISSUE TITLE
/environment back to empty in a .sif file

### ISSUE THREAD

**Issue by bs340248** [sylabs/singularity#3414] opened 2024-11-29 10:06 UTC
Dear developer,

I am using singularity-ce version 4.2.1-focal on Debian 11. I prepared a writable sandbox named amber24_28Nov2024 for my software with the environment added in /environment file in the sandbox.

A testing run with the following command gives me the correct location of the binary.
`singularity exec --nv /scratch/amber24_28Nov2024 which pmemd.cuda`

Thus, I packed the sandbox into a image file using the build command.
`singularity build --fakeroot amber24_28Nov2024.sif amber24_28Nov2024`

However, a testing run with the image file cannot find the software. 
`singularity exec --nv /scratch/amber24_28Nov2024.sif which pmemd.cuda`

I found out it was because the file /environment in the sif image is set back to default with all my custom environment code removed. Did I do something wrong or did I encounter a bug?

Best,

Wang Yin

**Comment by thvaisa** [comment] 2024-11-29 10:34
@bs340248 maybe the same as this one: https://github.com/sylabs/singularity/issues/3353

if it is the same reason, then you will need to downgrade to 4.1.5 or wait for the next release. Apptainer had the same bug at least 2 months ago but I have not tried their latest release

**Comment by bs340248** [comment] 2024-11-29 11:03
Than you for your reply. 
If this is a bug, a quick workaround would be creating a .sh file with custom environment code in `/.singularity.d/env/` folder.

**Comment by dtrudg** [comment] 2024-11-29 11:38
Yes, this is a duplicate of #3353 which has been fixed in the `main` and `release-4.2` branches, but not yet part of a release.

You may wish to build singularity directly from the `release-4.2` branch if this is causing significant problems.

**Closed by dtrudg** 2024-11-29 11:38 UTC
