### ISSUE TITLE
Singularity Run Error under Docker Desktop for MacOS on Apple Silicon

### ISSUE THREAD

**Issue by matthewparkinsondes** [sylabs/singularity#234] opened 2021-08-11 04:10 UTC
Received an error running the following under Docker Desktop (3.5.2) for MacOS X (11.5.1) on Apple Silicon (MacBook Pro 13-inch, M1, 2020).

`docker run --privileged quay.io/singularity/singularity:v3.8.1 run docker://hello-world`

```
ERROR  : Failed to spawn stage 1
```

However, have been successful with the following.

`docker run quay.io/singularity/singularity:v3.8.1 --version`
```
singularity-ce version 3.8.1
```

Is anyone else able to reproduce this error?

**Comment by dtrudg** [comment] 2021-08-11 13:23
The image `quay.io/singularity/singularity:v3.8.1` is an AMD64 image. As a first step to looking into this, it would be worth building an ARM64 docker container with SingularityCE in it, and seeing if you have the same problem.

I can run the same nested singularity inside docker without issue on an intel mac, suggesting there is something going on with the AMD64 -> ARM64 translation that has to happen when running an AMD64 container on an ARM64 (Apple Silicon) mac.

**Comment by dtrudg** [comment] 2021-08-11 13:31
See Docker Desktop notes:

> However, attempts to run Intel-based containers on Apple Silicon machines under emulation can crash as qemu sometimes fails to run the container. In addition, filesystem change notification APIs (inotify) do not work under qemu emulation. Even when the containers do run correctly under emulation, they will be slower and use more memory than the native equivalent.

> In summary, running Intel-based containers on Arm-based machines should be regarded as “best effort” only. We recommend running arm64 containers on Apple Silicon machines whenever possible

https://docs.docker.com/docker-for-mac/apple-silicon/

**Comment by matthewparkinsondes** [comment] 2021-08-13 22:22
Additional details are provided below (through enabling debug mode).

`docker run -it quay.io/singularity/singularity:v3.8.1 -d run docker://hello-world`

```
DEBUG   [U=0,P=1]          unsquashfsSandboxCmd()        Calling wrapped unsquashfs: singularity [-q exec --no-home --no-nv --no-rocm -C --no-init --writable -B /tmp/rootfs-511740430:/image -B /sbin/unsquashfs:/sbin/unsquashfs:ro -B /lib/ld-musl-x86_64.so.1:/lib/ld-musl-x86_64.so.1:ro -B /lib/libz.so.1:/lib/libz.so.1:ro -B /usr/lib/liblzma.so.5:/usr/lib/liblzma.so.5:ro -B /usr/lib/liblzo2.so.2:/usr/lib/liblzo2.so.2:ro -B /usr/lib/liblz4.so.1:/usr/lib/liblz4.so.1:ro /tmp/rootfs-511740430/tmp-rootfs-364707599 /sbin/unsquashfs -d /image/root /image/archive-277738005]
```

```
FATAL   [U=0,P=1]          execStarter()                 while extracting /root/.singularity/cache/oci-tmp/0fe98d7debd9049c50b597ef1f85b7c1e8cc81f59c8d623fcb2250e8bec85b38: root filesystem extraction failed: extract command failed: ERROR  : Failed to spawn stage 1
```

```
: exit status 1
```

**Comment by matthewparkinsondes** [comment] 2021-08-16 06:01
Have now built the following Dockerfile under Docker Desktop (3.6.0) for MacOS X (11.5.2) on Apple Silicon (MacBook Pro 13-inch, M1, 2020) using the following command.
`docker build -t singularity_arm64:v3.8.1 .`

**Dockerfile**
```
FROM ubuntu:20.04

RUN export DEBIAN_FRONTEND=noninteractive && \
    apt-get update && apt-get install -y \
    build-essential \
    libssl-dev \
    uuid-dev \
    libgpgme11-dev \
    squashfs-tools \
    libseccomp-dev \
    wget \
    pkg-config \
    git \
    cryptsetup

RUN export VERSION=1.16.4 OS=linux ARCH=arm64 && \
  wget https://dl.google.com/go/go$VERSION.$OS-$ARCH.tar.gz && \
  tar -C /usr/local -xzvf go$VERSION.$OS-$ARCH.tar.gz && \
  rm go$VERSION.$OS-$ARCH.tar.gz

RUN echo 'export PATH=/usr/local/go/bin:$PATH' >> ~/.bashrc

RUN export VERSION=3.8.1 && \
    wget https://github.com/sylabs/singularity/releases/download/v${VERSION}/singularity-ce-${VERSION}.tar.gz && \
    tar -xzf singularity-ce-${VERSION}.tar.gz && \
    cd singularity-ce-${VERSION}

RUN export VERSION=3.8.1 && \
    . ~/.bashrc && \
    cd singularity-ce-${VERSION} && \
    ./mconfig && \
    make -C builddir && \
    make -C builddir install

ENTRYPOINT ["/usr/local/bin/singularity"]
```

Checking the Singularity version.
`docker run singularity_arm64:v3.8.1 --version`
```
singularity-ce version 3.8.1
```

Performing the test shows it works as expected.
`docker run --privileged singularity_arm:v3.8.1 run docker://hello-world`
```
INFO:    Converting OCI blobs to SIF format
INFO:    Starting build...
Getting image source signatures
Copying blob sha256:109db8fad215b74f60f184ceb168a8ceefed5acc457e23c87c306616a0c8cc0d
Copying config sha256:69ff38a7d4f858e5f81966df4483877fe230447ae3af22c7b437b24b6b84cb83
Writing manifest to image destination
Storing signatures
2021/08/16 05:57:17  info unpack layer: sha256:109db8fad215b74f60f184ceb168a8ceefed5acc457e23c87c306616a0c8cc0d
INFO:    Creating SIF file...

Hello from Docker!
This message shows that your installation appears to be working correctly.

To generate this message, Docker took the following steps:
 1. The Docker client contacted the Docker daemon.
 2. The Docker daemon pulled the "hello-world" image from the Docker Hub.
    (arm64v8)
 3. The Docker daemon created a new container from that image which runs the
    executable that produces the output you are currently reading.
 4. The Docker daemon streamed that output to the Docker client, which sent it
    to your terminal.

To try something more ambitious, you can run an Ubuntu container with:
 $ docker run -it ubuntu bash

Share images, automate workflows, and more with a free Docker ID:
 https://hub.docker.com/

For more examples and ideas, visit:
 https://docs.docker.com/get-started/
```

**Comment by matthewparkinsondes** [comment] 2021-08-16 06:51
The following web page provides details for building multi-arch images for ARM64 and AMD64 with Docker Desktop.

https://www.docker.com/blog/multi-arch-images/

**Comment by dtrudg** [comment] 2021-08-16 14:33
@matthewparkinsondes - Glad to see this works as expected with an ARM64 docker container of SingularityCE. Since the issue is localized to the AMD64 -> ARM64 translation that is happening on the M1 Mac when running an AMD64 container, this is not something that we'll be able to address in SingularityCE code.

The images at quay.io/singularity are not managed by us, so we can't directly add an ARM64 variant there. They come from https://github.com/singularityhub/singularity-docker which is the work of .@vsoch here. It might be an idea to open an issue in that repository regarding the possibility (or not) of ARM64 images on quay.io.

**Comment by vsoch** [comment] 2021-08-16 17:04
@matthewparkinsondes I'd be happy to add this for you (and I have a PR ready to go) if you can show me a Dockerfile that can correctly build for arm. Note that I'm currently using qemu to be able to manage that (has worked for other projects I work on).

**Comment by dtrudg** [comment] 2021-08-16 22:07
Closing here in favor of: https://github.com/singularityhub/singularity-docker/pull/15

**Closed by dtrudg** 2021-08-16 22:07 UTC
Labels: wontfix, arm64

**Comment by matthewparkinsondes** [comment] 2021-08-18 23:35
The following scripts work in Docker Desktop.

They build a single Docker Image which supports execution on both amd64 and arm64.

The resulting Docker Image is pushed to the Docker Hub account provided.

The script has been run and produced the following Docker Image which is publicly available.

vamattparkinson/singularity:v3.8.1

Example commands to test out this image are as follows (these can be executed on both an amd64 platform and an arm64 platform, for example a MacBook Pro M1).

```
docker run --rm vamattparkinson/singularity:v3.8.1 --version
docker run --rm --entrypoint= vamattparkinson/singularity:v3.8.1 cat /log
docker run --rm --privileged vamattparkinson/singularity:v3.8.1 run docker://hello-world
```

**build_singularity.sh**
```
export OS=linux
export OS_IMAGE=ubuntu:20.04
export GO_VERSION=1.16.4
export SINGULARITY_VERSION=3.8.1

export DOCKER_HUB_ACCOUNT=vamattparkinson
export PLATFORM=${OS}/amd64,${OS}/arm64

export BUILT_IMAGE=${DOCKER_HUB_ACCOUNT}/singularity:v${SINGULARITY_VERSION}

docker login -u ${DOCKER_HUB_ACCOUNT}
docker buildx create --use --name builder
docker buildx create --append --name builder
docker buildx build \
       --build-arg OS \
       --build-arg OS_IMAGE \
       --build-arg GO_VERSION \
       --build-arg SINGULARITY_VERSION \
       -t ${BUILT_IMAGE} \
       --platform ${PLATFORM} --push .
docker buildx rm builder
```

**Dockerfile**
```
ARG OS_IMAGE

FROM --platform=${TARGETPLATFORM} ${OS_IMAGE}

ARG OS
ARG TARGETPLATFORM
ARG BUILDPLATFORM
ARG SINGULARITY_VERSION
ARG GO_VERSION

RUN echo "Running on ${BUILDPLATFORM}, building Singularity v${SINGULARITY_VERSION} for ${TARGETPLATFORM}" > /log

RUN export DEBIAN_FRONTEND=noninteractive && \
    apt-get update && apt-get install -y \
    build-essential \
    libssl-dev \
    uuid-dev \
    libgpgme11-dev \
    squashfs-tools \
    libseccomp-dev \
    wget \
    pkg-config \
    git \
    cryptsetup

RUN export ARCH=$(echo ${TARGETPLATFORM} | cut -f2 -d'/') && \
    export GO_ARCHIVE=go${GO_VERSION}.${OS}-${ARCH}.tar.gz && \
    wget https://dl.google.com/go/${GO_ARCHIVE} && \
    tar -C /usr/local -xzvf ${GO_ARCHIVE} && \
    rm ${GO_ARCHIVE}

RUN echo 'export PATH=/usr/local/go/bin:${PATH}' >> ~/.bashrc

RUN export SINGULARITY_ARCHIVE=singularity-ce-${SINGULARITY_VERSION}.tar.gz && \
    wget https://github.com/sylabs/singularity/releases/download/v${SINGULARITY_VERSION}/${SINGULARITY_ARCHIVE} && \
    tar -xzf ${SINGULARITY_ARCHIVE} && \
    rm ${SINGULARITY_ARCHIVE}

RUN export SINGULARITY_DIR=singularity-ce-${SINGULARITY_VERSION} && \
    . ~/.bashrc && \
    cd ${SINGULARITY_DIR} && \
    ./mconfig && \
    make -C builddir && \
    make -C builddir install && \
    cd .. && \
    rm -rf ${SINGULARITY_DIR}

ENTRYPOINT ["/usr/local/bin/singularity"]
```

**Comment by vsoch** [comment] 2021-08-18 23:37
Thanks @matthewparkinsondes - could you copy paste this into the PR where I'm working? I can't work on it imminently but I'll make sure to look closer soon.

**Comment by vsoch** [comment] 2021-08-19 18:36
hey @matthewparkinsondes I just deployed a tag `arm-test` with Singularity 3.8.1 to Quay https://quay.io/repository/singularity/singularity?tab=tags. Could you take a look? It should have an updated go version in it too.

**Comment by vsoch** [comment] 2021-08-19 18:37
Actually that particular one probably doesn't have the arm yet (it's still building) I'll ping when it's ready.

**Comment by vsoch** [comment] 2021-08-19 19:00
okay give it a shot! https://quay.io/repository/singularity/singularity/manifest/sha256:7cac55b596d91e7eb08b7d1bc4531aeb344aee60d3c54bda7556152135a266a9

I guess Quay doesn't automatically detect that it's arm64? So we will need to release different tags for each one?

**Comment by dtrudg** [comment] 2021-08-19 19:50
> I guess Quay doesn't automatically detect that it's arm64? So we will need to release different tags for each one?

@vsoch - there's definitely some way of having different architectures under the same tag on Quay. E.g. see:

https://quay.io/repository/prometheus/node-exporter?tab=tags

If you hover over the penguin icons, each one is representing a different architecture.

**Comment by vsoch** [comment] 2021-08-19 20:11
Huh, I thought it would detect the build automatically. Could someone take a look at the -arm container just pushed here and tell me if it's actually arm? If not, then that's the issue! All I did was add --platform as arm64 to the build (but maybe there is something else I need to do). https://quay.io/repository/singularity/singularity?tab=tags. This is my first time building arm with singularity so thanks for the help!

**Comment by dtrudg** [comment] 2021-08-19 20:34
Can confirm that v3.8.2-arm64 is definitely an ARM64 container that works on my raspberry pi 4... cheers!

**Comment by vsoch** [comment] 2021-08-19 20:48
yay!! So I'm disappointed to not have the cute penguin tags, but I'm pretty happy with this for now. Some future contributor (or me) can come back to this and look into the tags again, but functionally it should work okay like this. Thanks for the help @dtrudg !

**Comment by matthewparkinsondes** [comment] 2021-08-20 10:58
@vsoch, I've also now confirmed the following image is ARM64.

`quay.io/singularity/singularity:v3.8.2-arm64`

Performing a 'docker inspect' reveals the following.

`"Architecture": "arm64"`

I have also now confirmed that it runs successfully within Docker Desktop on a MacBook Pro M1.

**Comment by matthewparkinsondes** [comment] 2021-08-21 00:32
@vsoch, I ran `docker inspect` again on this image.

`quay.io/singularity/singularity:v3.8.2-arm64`

I noticed it still references 3.8.1 in a couple of the labels.

"SINGULARITY_VERSION=3.8.1"

**Comment by vsoch** [comment] 2021-08-21 00:44
Ah, good catch! I was testing with 3.8.1 and did update the 3.8.2 recipe for slim, but not for the regular it seems! https://github.com/singularityhub/singularity-docker/blob/v3.8.2/Dockerfile.arm.

I'll get a fix in asap! It takes 25 minutes to build so I'll ping here when it's done.
