### ISSUE TITLE
group mapping seems not consistent

### ISSUE THREAD

**Issue by prod-feng** [sylabs/singularity#2635] opened 2024-02-07 03:47 UTC
**Version of Singularity**
What version of Singularity are you using? Run:

```
$ singularity --version
```
Rocky Linux release 8.4

singularity/4.0.2

**Describe the bug**

The groups of the user in the singularity image seem wrong, with "id" command, different argument

[fenz@node014 /]$ id
uid=1111(fenz) gid=1111(fenz) groups=1111(fenz),65534(nobody)
[fenz@node014 /]$ id fenz
uid=1111(fenz) gid=1111(fenz) groups=1111(fenz),20001(mygroup)

**To Reproduce**

**Expected behavior**

Other binded folders are mounted as owned by "nobody". So user "fenz" then be able to delete these files there that may node belong to "fenz".

**OS / Linux Distribution**
Which Linux distribution are you using?
```
$ cat /etc/os-release

Rocky Linux release 8.4

```

**Installation Method**
Write here how you installed SingularityCE. Eg. RPM, source.

Source
**Additional context**
Anything else which might be relevant. E.g. if the bug only occurs on a specific filesystem, or kernel version etc.

**Comment by prod-feng** [comment] 2024-02-07 14:11
Yes, I am running in user name space(fake root), this image is also built by myself in fake root mode too.

Adding the --no-setgroups seems does not change anything, all bind folders from hosts are owned by "nobody".

Thanks!

**Comment by prod-feng** [comment] 2024-02-07 14:45
run:
 singularity exec rstudio-rocky8.4.sif /bin/bash

version 4 show the problem, mounts all bind host folder as owned by "nobody".

While:

Used the local singularity 3.10.4-1.el8, then looks OK:

Singularity> ls -l /lustre/software/
total 140381700
drwxrwsr-x  3 1125     20012        4096 Oct 19  2022 7zip
drwxrwsr-x 10 1103     20012        4096 Sep 20  2021 AICON2


One even weird thing I found:

one file named "qqqq.log2" in my HOME, on the host node chown to root. singularity 3 mount it and see it owned by root in the container.
Inside the container, I can change the contents of it(owned by root) using my own user account. After forced to save it, it changed the file's ownership as my user account(fenz). I can also delete the file even it is owned by "root"

On host node:
chown root: qqqq.log2

Singularity> ls -l
-rw-r--r--   1 fenz  fenz          8 Feb  7 09:26 qqqq.log2~
-rw-r--r--   1 root     root           12 Feb  7 09:27 qqqq.log2
Singularity> rm qqqq.log2
rm: remove write-protected regular file 'qqqq.log2'? y
Singularity> 

We are using Lustre as HOME.

**Comment by prod-feng** [comment] 2024-02-07 16:02
Also in singularity 3.10.4-1.el8, the "id" command with/without arguments give the same output. Not like Singularity 4 which maps a "nobody" group to the user.

**Comment by prod-feng** [comment] 2024-02-07 16:06
OK I see, our  singularity 3.10.4-1.el8 is in segued mode.

**Comment by prod-feng** [comment] 2024-02-07 17:01
For the version 3 and 4, my real question now is:

If I bind a host node's /usr/bin to the container, then all the files are mapped to user and group of nobody:nobody. While as a use to run the container, I am also mapped to be a member of "nobody" group(version 4). Is it assured that I (as regular user, and a member of  "nobody" in the container) can NOT delete/change any files in the bind /usr/bin folders, even they are "group" writable?

Thanks!

**Comment by dtrudg** [comment] 2024-02-07 17:05
It seems that you are running different versions in different configurations. As far as I can tell from what you have mentioned, the behaviour you see is as expected, due to the limitations of user namespaces - which are used when running with `--fakeroot` or non-setuid.

Also note that...

> Adding the --no-setgroups seems does not change anything, all bind folders from hosts are owned by "nobody".

This is as expected, as I mentioned above:

> Note that if you are in user namespace mode, then a flag --no-setgroups is available that can preserve group-based access to files on the host, but will not change the output of id.

Everything appears as 'nobody' in the container. The `--no-setgroups` flag just allows file access through the groups to still work on the host, even though they appear as 'nobody' in the container.

>One even weird thing I found:

>one file named "qqqq.log2" in my HOME, on the host node chown to root. singularity 3 mount it and see it owned by root >in the container.
Inside the container, I can change the contents of it(owned by root) using my own user account. After forced to save it, it changed the file's ownership as my user account(fenz). I can also delete the file even it is owned by "root"

On Linux systems, the ability to delete a file is *not* due to the permissions on the file. Deletion is controlled by the permissions on the directory that contains the file. This is a commonly misunderstood - e.g. https://askubuntu.com/questions/1003461/why-can-i-delete-a-755-file-when-im-not-the-owner

**Comment by prod-feng** [comment] 2024-02-07 17:21
Thanks very much, dtrudg!

**Comment by dtrudg** [comment] 2024-02-07 17:28
Let's close this, as there's not a bug here - it's more a case of having to understand the differences between ways in which singularity can be run, and the limitations.

If you have questions about usage, then opening a Q&A discussion would be best to follow-up - https://github.com/sylabs/singularity/discussions/categories/q-a

**Closed by dtrudg** 2024-02-07 17:28 UTC
Labels: needs more info
