### ISSUE TITLE
error installing singularity

### ISSUE THREAD

**Issue by karthickbrlab** [sylabs/singularity#2814] opened 2024-04-10 10:12 UTC
Hi
kindly help me to sort this out
make -C builddir
make: Entering directory '/home/ubuntu/go/src/github.com/sylabs/singularity-3.8.7/builddir'
/bin/sh: 1: /home/ubuntu/go/src/github.com/sylabs/singularity-3.8.7/scripts/go-generate: Permission denied
make: *** [Makefile:165: /home/ubuntu/go/src/github.com/sylabs/singularity-3.8.7/internal/pkg/buildcfg/config.go] Error 126
make: Leaving directory '/home/ubuntu/go/src/github.com/sylabs/singularity-3.8.7/builddir'

**Comment by tri-adam** [comment] 2024-04-10 14:09
Hi @karthickbrlab, please follow the instructions in https://github.com/sylabs/singularity/blob/main/INSTALL.md if you wish to install from source. Also note that Singularity 3.8.7 is very old, I would recommend updating to the latest release (https://github.com/sylabs/singularity/releases). Depending on the version of Ubuntu you are running, a pre-built `.deb` may also be available in the releases section.

**Comment by karthickbrlab** [comment] 2024-04-11 06:29
Hi
I have installed the newer version of singularity..but im unable to configure, as host go compiler not found. although i have recent go version.


$ go version
go version go1.22.2 linux/amd64

./mconfig 
Configuring for project `singularity-ce' with languages: C, Golang
=> running pre-basechecks project specific checks ...
=> running base system checks ...
 checking: host C compiler... cc
 checking: host C++ compiler... c++
 checking: host Go compiler (at least version 1.20)... not found!
mconfig: could not complete configuration

**Comment by tri-adam** [comment] 2024-04-12 14:53
OK, that looks like a problem with your Go installation. The command that is run by `config` to check for the Go compiler is:

```sh
$ go run mlocal/checks/version.go go1.20
Found Go release tag go1.20.
```

Running that might shed some light on why the check is failing.

The most common thing that causes that check to fail is having upgraded Go over a previous installation rather than removing the old installation first. It might be worth re-installing Go following the instructions at https://go.dev/doc/install to rule that out.

**Comment by dtrudg** [comment] 2024-06-14 09:19
Closing as there hasn't been any follow-up. If the issue isn't resolved, please feel free to re-open this with some additional information about how exactly you installed Go.

**Closed by dtrudg** 2024-06-14 09:19 UTC
