### ISSUE TITLE
Fatal error binding from `/tmp/xxxx` when /var/tmp is symlink -> /tmp

### ISSUE THREAD

**Issue by charmoniumQ** [sylabs/singularity#1331] opened 2023-02-13 20:25 UTC
**Version of Singularity**

singularity-ce version 3.10.3

**Describe the bug**

The error message when mounting paths from `/tmp` when `mount tmp = yes` is incorrect

**To Reproduce**

```bash
$ # edit singularity.conf to set "mount tmp = yes"
$ grep 'mount temp' /path/to/etc/singularity/singularity.conf
mount temp = yes
$ mkdir /tmp/test
$ singularity exec -B /tmp/test https://depot.galaxyproject.org/singularity/python:3.8.3 pwd
WARNING: Skipping mount /home/azureuser/spack/opt/spack/linux-ubuntu22.04-zen2/gcc-11.3.0/singularityce-3.10.3-z5qu45ho72nvsy4rpcyd4eqrop35tnbe/var/singularity/mnt/session/etc/resolv.conf [files]: /etc/resolv.conf doesn't exist in container
FATAL:   container creation failed: mount /tmp/test->/tmp/test error: while mounting /tmp/test: destination /tmp/test doesn't exist in container
```

**Expected behavior**

The error message seems says, "destination /tmp/test doesn't exist in container". This is a red herring, as the following will work:

```bash
$ sudo mkdir -p /a/b/c
$ sudo chown $USER:$GROUP /a/b/c                                                                                                                     
$ singularity exec -B /a/b/c https://depot.galaxyproject.org/singularity/python:3.8.3 pwd                                                            WARNING: Skipping mount /home/azureuser/spack/opt/spack/linux-ubuntu22.04-zen2/gcc-11.3.0/singularityce-3.10.3-z5qu45ho72nvsy4rpcyd4eqrop35tnbe/var/singularity/mnt/session/etc/resolv.conf [files]: /etc/resolv.conf doesn't exist in container
/
```

and the true solution to this error is to set `mount temp = no` in `/path/to/etc/singularity/singularity.conf`.

```bash

$ # edit singularity.conf to set "mount tmp = no"
$ grep 'mount temp' /path/to/etc/singularity/singularity.conf
mount temp = no
$ mkdir /tmp/test
$ singularity exec -B /tmp/test https://depot.galaxyproject.org/singularity/python:3.8.3 pwd
/
```

**OS / Linux Distribution**

```
$ cat /etc/os-release 
PRETTY_NAME="Ubuntu 22.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.1 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```

**Installation Method**

Spack

**Additional context**

While incorrect error messages may seem unimportant, they can cost days of user time. See [this](https://github.com/nf-core/eager/issues/894#issuecomment-1428611633).

Note that this bug also happens in Apptainer ([bug rep](https://github.com/sylabs/singularity/issues/1331)).

**Comment by dtrudg** [comment] 2023-02-14 13:09
Also, just a quick note that as a workaround for this issue, the `--no-mount tmp` flag can be used to avoid changing `singularity.conf` (since a working /tmp in the container will be expected by a lot of tools). 

```
$ singularity shell --no-mount tmp -B /tmp/test https://depot.galaxyproject.org/singularity/python:3.8.3
INFO:    Converting SIF file to temporary sandbox...
Singularity> 
```

**Comment by charmoniumQ** [comment] 2023-02-14 17:50
> Please could you give exact information on how the software was installed from Spack.

```bash
$ spack env create test
$ spack add singularityce~suid e2fsprogs squashfuse
$ spack install
$ singularity exec -B /tmp/test https://depot.galaxyproject.org/singularity/python:3.8.3 pwd
INFO:    Converting SIF file to temporary sandbox...
WARNING: Skipping mount /home/sam/.local/share/spack/opt/spack/linux-ubuntu22.04-skylake/gcc-11.3.0/singularityce-3.10.3-yvpjjnkr7epa4l2isxdxazehaayj247d/var/singularity/mnt/session/etc/resolv.conf [files]: /etc/resolv.conf doesn't exist in container
INFO:    Cleaning up image...
FATAL:   container creation failed: mount /tmp/test->/tmp/test error: while mounting /tmp/test: destination /tmp/test doesn't exist in container
$ spack spec
<snipped output>
singularityce@3.10.3%gcc@11.3.0+network~suid build_system=makefile arch=linux-ubuntu22.04-skylake
    ^conmon@2.1.5%gcc@11.3.0 build_system=makefile arch=linux-ubuntu22.04-skylake
    ^go@1.18.1%gcc@11.3.0 build_system=generic arch=linux-ubuntu22.04-skylake
    ^squashfs@4.5.1%gcc@11.3.0+gzip~lz4~lzo~xz~zstd build_system=makefile default_compression=gzip arch=linux-ubuntu22.04-skylake
```

> Package managers such as Spack are often installing SingularityCE without setuid (I believe that's the case here)

It breaks with and without setuid. The previous block was without suid.

```bash
$ spack remove singularityce~suid
$ spack add singularityce+suid
$ spack concretize --force
$ spack install
$ # we need an extra step, since spack is a non-root package manager
$ sudo $(which spack_perms_fix.sh)
$ ls -l $(dirname $(dirname $(readlink $(which singularity))))/etc/singularity/singularity.conf
-rw-r--r-- 1 root sam 14956 Feb 13 11:11 /blah/blah/etc/singularity/singularity.conf
$ singularity exec -B /tmp/test https://depot.galaxyproject.org/singularity/python:3.8.3 pwd
WARNING: Skipping mount /home/sam/.local/share/spack/opt/spack/linux-ubuntu22.04-skylake/gcc-11.3.0/singularityce-3.10.3-sgja7zjhvtdspreh3bbslbuvkiecw27u/var/singularity/mnt/session/etc/resolv.conf [files]: /etc/resolv.conf doesn't exist in container
FATAL:   container creation failed: mount /tmp/test->/tmp/test error: while mounting /tmp/test: destination /tmp/test doesn't exist in container
```

> Please don't assume that we might consider this unimportant.

Sorry, my bad.

> It is not necessarily an incorrect error message - the error message may be correct but there is a bug causing the circumstances that lead to it.

Very possible. I just meant that the error message is not consistent with the behavior of the program (breaks with `/tmp`, works with any other path, even if that path does not exist in the container).

> In addition, please note that the initial problem in the linked nfcore/eager issue is not the same as you are experiencing, as it does not involve the tmp mount.

Yes, I was referring to a [specific comment](https://github.com/nf-core/eager/issues/894#issuecomment-1428611633) in that issue, not the issue itself.

**Comment by dtrudg** [comment] 2023-02-15 16:06
Thanks for the extra information. We'll look into this for the next patch release.

**Comment by dtrudg** [comment] 2023-02-23 13:57
Having looked at this a bit more, I think the issue is related to the fact that in this image, `/var/tmp` is a symlink back to `/tmp`. Singularity is trying to mount `/var/tmp` and `/tmp` separately... but the resolution of the symlink through `/var/tmp` -> `/tmp` means we ending up masking the bind point in the overlay that has been setup.

I believe this can be fixed with some special handling to make sure `/tmp` and `/var/tmp` don't get mounted separately, when they resolve to the same place in the image.

**Comment by charmoniumQ** [comment] 2023-02-23 19:09
Lmk if there is anything you want me to test out and send you the logs. Spack supports installing from a specific git commit without too much pain.

**Comment by dtrudg** [comment] 2023-02-24 14:40
> Lmk if there is anything you want me to test out and send you the logs. Spack supports installing from a specific git commit without too much pain.

Will do. This is not actually a simple fix, due to the way the code is structured, and binds are queued.

In view of the time it's likely to take, it might not be in the next patch release, but we'll try. There are some things without workaround that might need to come out sooner.

**Closed** 2023-09-21 14:44 UTC
Labels: bug
