### ISSUE TITLE
macro not defined error in aarch64 yum CentOS 7 bootstrap

### ISSUE THREAD

**Issue by shmily0000** [sylabs/singularity#1703] opened 2023-05-25 09:02 UTC
Hello, using Centos to install Singularity here uses rpm installation, so there are no files such as Singularity.spec. The Singularity version is 3.11.3-1.el7, and the Centos version is Centos-release-7-9.2009.

The content of the def file is as follows

BootStrap: yum

OSVersion: 7

MirrorURL: http://mirror.centos.org/altarch/% {OSVERSION}/os/aarch64/

Include: /usr/bin/yum

%runscript

echo "This is what happens when you run the container..."

%post

echo "Hello from inside the container"

/usr/bin/yum -y install vim-minimal

![image](https://github.com/sylabs/singularity/assets/106640220/a9ecfccc-173e-4012-bd2e-cf2471b2afc7)
![image](https://github.com/sylabs/singularity/assets/106640220/ff6c1049-cc71-4f95-ab71-10d9fdfdd44a)

![image](https://github.com/sylabs/singularity/assets/106640220/7ff1b603-8b1f-4964-b1a7-b6952ccf6895)
![image](https://github.com/sylabs/singularity/assets/106640220/78b4a3c3-35c9-4309-a37a-6fa5fb94c0bb)

After referring to the issue # 5281,url is https://github.com/apptainer/singularity/issues/5281； the execution failed. However, the singularity.spec file and the corresponding version of the tar package mconfig file were placed in the required location, but the execution still failed,

Can you provide me with an available def to create a SIF image? By the way, please help me see where the problem is

**Comment by dtrudg** [comment] 2023-05-25 10:17
Hello. I'm afraid that the issue 5281 you found is not relevant here. Using `mconfig` and `rpmbuild` is for building an RPM for SingularityCE itself, rather than anything to do with building a container from a definition file.

The error you are seeing appears to be because on the host system the `rpm` macro `_db_backend` or `_db_path` is not defined.

Please could you provide output of the following command, run on the host?

```
rpm --eval "%{_db_backend}"
rpm --eval "%{_dbpath}"
```

These macros should be defined in any `rpm` installation, so I'm not sure exactly what is going on here.

**Comment by dtrudg** [comment] 2023-06-19 16:22
Hello. As there has been no follow-up for several weeks, and we've not been able to reproduce the problem, I'm going to close this issue. Please feel free to re-open it if you can provide the requested information.

**Closed by dtrudg** 2023-06-19 16:22 UTC
Labels: needs more info
