### ISSUE TITLE
FATAL:   shell /bin/sh doesn't exist in container

### ISSUE THREAD

**Issue by dejangrubisic** [sylabs/singularity#1497] opened 2023-03-30 17:21 UTC
**Version of Singularity**
singularity version 3.5.3-1.el7

**Describe the bug**
I created a singularity image and push it on the hub. Now I want to download it as a sandbox. Hopefully, I won't need to pull the image.sif first and then convert it to the sandbox, since it takes more space. So I found a command to create the sandbox from the cloud, but I cannot enter it since it fails with :

`FATAL:   shell /bin/sh doesn't exist in container`

**To Reproduce**
```
singularity build --sandbox /scratch/sandbox library://dejang96/compiler2/ubuntu:20.04
singularity shell /scratch/sandbox/
```

**Expected behavior**
I would expect to enter the sandbox.

PS. This work if I create the first image.sif and then make sandbox with
```
singularity pull --arch amd64 library://dejang96/compiler2/ubuntu:20.04
singularity build --sandbox sandbox ubuntu_20.04.sif
```

**OS / Linux Distribution**
Which Linux distribution are you using?
```
Host: Red Hat Enterprise Linux Server 7.6 (Maipo)
Container: Ubuntu 20.04
```

**Installation Method**
The binary is provided at the cluster. I have no sudo privileges.

**Comment by dtrudg** [comment] 2023-04-02 18:40
Hello. I'm afraid Singularity 3.5.3 is now very old and not supported. The current version of SingularityCE is 3.11.1.

It is likely that the issue has been fixed in newer versions of Singularity. I cannot reproduce it with 3.11.1. Please update, or request that your system administrator updates Singularity.

If the issue persists in a current version of Singularity, please feel free to reopen the issue.

**Closed by dtrudg** 2023-04-02 18:40 UTC
Labels: bug
